<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Postcode_textbox</name>
   <tag></tag>
   <elementGuidId>8d3c8716-c43f-4963-b896-1a0dcc19dddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postalcode</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
