<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rhithmic_professional_trader_radiobutton</name>
   <tag></tag>
   <elementGuidId>35578715-88dd-441a-884f-fe22ff83a6fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[value='prof']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
