<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rhithmic_platform_radiobutton</name>
   <tag></tag>
   <elementGuidId>20f9c68e-08ce-42b8-931f-f7731995acfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#platformContainer3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
